language: node_js

node_js:
  - 0.10
  - 0.12
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
  - "iojs"

notifications:
  email:
    recipients:
      - magic@wizardtales.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/509c88551a18006fe93f
    on_success: change
    on_failure: always
    on_start: false

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs-3"
    - node_js: "iojs"

services:
  - mongodb

sudo: false

cache:
  npm: true
  directories:
    - node_modules

addons:
  mariadb: "10.0"

before_script:
    - until nc -z localhost 27017 ; do echo Waiting for MongoDB; sleep 1; done
    - mysql -e "create database db_migrate_test;"
    - createdb db_migrate_test
    - cp test/db.config.ci test/db.config.json
