language: node_js

node_js:
  - 4.0
  - 4.2
  - 5
  - 6
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
  - "iojs"

notifications:
  email:
    recipients:
      - magic@wizardtales.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/509c88551a18006fe93f
    on_success: change
    on_failure: always
    on_start: false

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6

sudo: false

cache:
  npm: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export CXX=g++-4.8; export CC=gcc-4.8;

before_script:
    - cp test/db.config.ci test/db.config.json
